### PR TITLE
Upload docs

### PR DESCRIPTION
**Pull request by Moredread**

### CODE REVIEW

**Comment by Moredread** [comment]
I'm not sure that this will work

**Comment by aepsil0n** [comment]
I don't think so, as it has to my secret to upload it to `aepsil0n.github.io`.

**Comment by aepsil0n** [comment]
Unless you hacked my account, of course. ;)

**Comment by Moredread** [comment]
Btw, you should revoke your secrets, see the announcement by travis awhile ago.

**Comment by Moredread** [comment]
This is still open, are you planning on merging it, or can I close it?

**Comment by aepsil0n** [comment]
By now I think it's not worth it, as there is [docs.rs](https://docs.rs/)

**Pull request closed without merging**
